### ISSUE TITLE
Can't run baseline algorithms.

### ISSUE THREAD

**Issue by XinyuWang2** [facebookresearch/hsd3#1]
Hi, I am trying to run some baseline codes, but I run into the same issue. I followed the requirements.txt and used gym==0.23.1.
Below is the output of the problem. Thanks.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Exception ignored in: <function VectorEnv.__del__ at 0x7fe9eac66e50>
Traceback (most recent call last):
  File "hsd3/env/lib/python3.8/site-packages/gym/vector/vector_env.py", line 215, in __del__
    self.close()
  File "hsd3/env/lib/python3.8/site-packages/gym/vector/vector_env.py", line 193, in close
    self.close_extras(**kwargs)
  File "hsd3/hucc/envs/thmp_vector_env.py", line 329, in close_extras
    if self._state != AsyncState.DEFAULT:
AttributeError: 'TorchAsyncVectorEnv' object has no attribute '_state'

**Comment by jgehring** [comment]
Can you try it with a lower gym version? I've been using a 0.18 version IIRC.

**Comment by jgehring** [comment]
I looked into this again and the environment code requires gym<0.22. I've updated requirements.txt to reflect that.
